### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by daknoxy** [ItinerisLtd/gf-loqate-bank-verification#34]
We I activate it on Wordpress 5.2.9, Php 7.2 I am getting a critical error is there an update to this plugin or can you advise?

**Comment by tangrufus** [comment]
Question:
- What is the error message?
- How did you installed the plugin?
- If installed via composer, what is the package name?

**Comment by daknoxy** [comment]
It is a Critical Error message, running Divi Theme not Composer. Installed via Plugin - Add New and Search and install
We are also running https://wordpress.org/plugins/address-email-and-phone-validation/ which is working ok https://oneilcare.com/online-contract/

Checked on error log and can see below, not sure if this relates

[06-Nov-2020 08:12:36 UTC] PHP Warning:  PHP Startup: SourceGuardian: Unable to initialize module
Module compiled with module API=20160303
PHP    compiled with module API=20170718
These options need to match
 in Unknown on line 0

**Comment by tangrufus** [comment]
The error message is unrelated to gf-loqate-bank-verification.
Ask your server admin to check the php installation (probably some php modules are not configured properly)

**Comment by daknoxy** [comment]
That was a previous error which has been fixed see below for error related to plugin

Error Details
=============
An error of type E_ERROR was caused in line 16 of the file /home2/crag/public_html/wp-content/plugins/gf_pcapredict/gf_pcapredict.php. Error message: Uncaught Error: Call to undefined function is_plugin_active() in /home2/crag/public_html/wp-content/plugins/gf_pcapredict/gf_pcapredict.php:16
Stack trace:
#0 /home2/crag/public_html/wp-settings.php(362): include_once()
#1 /home2/crag/public_html/wp-config.php(97): require_once('/home2/crag/pub...')
#2 /home2/crag/public_html/wp-load.php(37): require_once('/home2/crag/pub...')
#3 /home2/crag/public_html/wp-admin/admin.php(34): require_once('/home2/crag/pub...')
#4 {main}
  thrown

**Comment by tangrufus** [comment]
Report to `gf_pcapredict`'s authors instead.
This repo is for https://wordpress.org/plugins/gf-loqate-bank-verification/
